### ISSUE TITLE
Trouble installing with snap

### ISSUE THREAD

**Issue by Seikatsu-exe** [Cr3atable/LinuxED#5]
I've no clue where to look for the client's index.js file, and found no documentation or help elsewhere.

**Comment by twnlink** [comment]
This issue is known however I'm not exactly sure how to correct it. I do not have a Linux box to test LED on at the moment so I'm not exactly sure where Discord is stored in Snap. I've also noticed that Snaps cannot reference files outside of themselves, meaning I'd have to put the ED folder inside of the Snap folder, which is easy, but unorganized. I may just remove Snap (and possibly Flatpak) support entirely.
This issue however will remain open until I've decided exactly what I'll do to to correct this, and have implemented that solution.
As an alternative solution, you can install Discord from https://discordapp.com (only on Debian based distros) or from your package manager.

**Comment by Seikatsu-exe** [comment]
I figured it out a day after I posted this, and installed with a custom path. If it's any help, index.js was located at ~/snap/discord/current/.config/discord/0.0.9/modules/discord_desktop_core

**Comment by twnlink** [comment]
I've implemented the directory you listed in commit 8d6fcb0ba68bede7a576a425ee659cdc950fcfb3, please update your LinuxED via the installer to use the new version with Snap implemented.
